### ISSUE TITLE
HTTPRoute with RequestRedirect results in invalid spec

### ISSUE THREAD

**Issue by lehmanju** [bjw-s-labs/helm-charts#390]
# Details

**What steps did you take and what happened:**

Used following snippet:
````
route:
  main:
    parentRefs:
      - name: paperless-web
        namespace: paperless
        sectionName: https
    hostnames:
      - paperless.lan
    rules:
      - backendRefs:
          - kind: Service
            port: 80
            name: app
  redirect:
    parentRefs:
      - name: paperless-web
        namespace: paperless
        sectionName: http
    hostnames:
      - paperless.lan
    rules:
      - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
````
This results in
````
# Source: app-template/templates/common.yaml
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: paperless-redirect
  labels:
    app.kubernetes.io/instance: paperless
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: paperless
    helm.sh/chart: app-template-3.7.2
  namespace: default
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: paperless-web
      namespace: paperless
      sectionName: "http"
  hostnames:
    - "paperless.lan"
  rules:
  - backendRefs:
    filters:
      - requestRedirect:
          scheme: https
          statusCode: 301
        type: RequestRedirect
````
where `backendRefs` is empty and thus rejected because its value is 'null'.

**What did you expect to happen:**

`backendRefs` should be missing if not set
