### ISSUE TITLE
Add `<name>.parentRefs[].port` in `route`

### ISSUE THREAD

**Issue by budimanjojo** [bjw-s-labs/helm-charts#399]
# Details

**Describe the solution you'd like:**
Currently there's no way to define `spec.parentRefs[].port` for `HTTPRoute` kind in this charts. It would be nice to have this.

**Anything else you would like to add:**
I know I can just use `<name>.parentRefs[].sectionName` and be happy. But I have multiple domain listeners inside my `Gateway` kind like so:
```yaml
spec:
  listeners:
    - name: https-0
      port: 443
      hostname: "*.myfirstdomain.com"
    - name: https-1
      port: 443
      hostname: "*.myseconddomain.com"
```

So, needing to remember what `sectionName` for the hostname is quite awkward, and it can't even be done when I want to expose the same service for both domains.

**Additional Information:**
