### ISSUE TITLE
Add `sessionPersistence` to `route`

### ISSUE THREAD

**Issue by tholinka** [bjw-s-labs/helm-charts#400]
# Details

**Describe the solution you'd like:**

The current version is missing [`sessionPersistence`](https://gateway-api.sigs.k8s.io/reference/spec/#sessionpersistence)

**Anything else you would like to add:**

Currently adding it with a `postRenderers`, and it works fine on Envoy Gateway, but Cilium Gateway seems to ignore it.

```yaml
  postRenderers:
    - kustomize:
        patches:
          # pin session to one pod so login doesn't get reset
          - target:
              kind: HTTPRoute
              name: *app
            patch: |
              - op: add
                path: /spec/rules/0/sessionPersistence
                value:
                  sessionName: [app name, can't use *app since it's a patch :(]
                  type: Cookie
                  absoluteTimeout: 24h
```

**Additional Information:**

Example rendered route:
```yaml
spec:
  hostnames:
  - app.domain.name
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: internal
    namespace: network
    sectionName: https
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: app
      namespace: network
      port: 80
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
    sessionPersistence:
      absoluteTimeout: 35m
      sessionName: app
      type: Cookie
```
