### ISSUE TITLE
from 3.7.3 to 4.0.0, persistence PVC name changed!

### ISSUE THREAD

**Issue by east4ming** [bjw-s-labs/helm-charts#414]
# Details

**What steps did you take and what happened:**

upgrade from 3.7.3 to 4.0.0

**What did you expect to happen:**

persistence PVC name keep same

**Anything else you would like to add:**

My values:

```
controllers:
    metatube:
        containers:
            metatube: ...
defaultPodOptions:
    enableServiceLinks: true
persistence:
    data:
        accessMode: ReadWriteOnce
        advancedMounts:
            metatube:
                metatube:
                    - path: /config
        size: 10Gi
```

values.yaml keep no change , but from 3.7.3 to 4.0.0:

![Image](https://github.com/user-attachments/assets/e5f6394b-a6e9-4159-8d6b-b78c1b4420f1)

**Additional Information:**
