### ISSUE TITLE
jobLabel should point to the label that contains the name of the job

### ISSUE THREAD

**Issue by halkeye** [bjw-s-labs/helm-charts#419]
# Details

**What steps did you take and what happened:**

Create a new service monitor (via app-template)
```
  serviceMonitor:
    main:
      serviceName: '{{ include "bjw-s.common.lib.chart.names.fullname" $ }}'
      endpoints:
        - port: http
          scheme: http
          path: /metrics
          interval: 60m
          scrapeTimeout: 1m
```

**What did you expect to happen:**

(to work<_< lol, jk, etc)

A new service is monitored with job="speedtest-exporter"

**What did happen:**

Service was created with job="serviceMonitor/monitoring/speedtest-exporter/0"

**Additional Information:**

According to the prometheus operator crd, jobLabel should be the name of the label, not the job name itself.
```
              jobLabel:
                description: |-
                  The label to use to retrieve the job name from.
                  `jobLabel` selects the label from the associated Kubernetes `Pod`
                  object which will be used as the `job` label for all metrics.

                  For example if `jobLabel` is set to `foo` and the Kubernetes `Pod`
                  object is labeled with `foo: bar`, then Prometheus adds the `job="bar"`
                  label to all ingested metrics.

                  If the value of this field is empty, the `job` label of the metrics
                  defaults to the namespace and name of the PodMonitor object (e.g. `<namespace>/<name>`).
                type: string
```

so by hard coding it to the release name, it'll never actually match anything unless I create a new label of "serviceMonitor/monitoring/speedtest-exporter/0"

**Suggested Resolutions:**

* Do Nothing / Remove the default - Same conclusion, but less misleading
* Change default jobLabel to "app.kubernetes.io/instance" or "app.kubernetes.io/name" or something
* Allow it to be overridden
