### ISSUE TITLE
offlline 4.0.1 not possible.

### ISSUE THREAD

**Issue by MrFreezeDZ** [bjw-s-labs/helm-charts#420]
# Details

**What steps did you take and what happened:**
I downloaded the source-code for 4.0.1 here: https://github.com/bjw-s-labs/helm-charts/archive/refs/tags/common-4.0.1.tar.gz

I extracted the file helm-charts-common-4.0.1.tar.gz with the command `tar -xvzf helm-charts-common-4.0.1.tar.gz`
I edited the file `helm-charts-common-4.0.1/charts/other/app-template/Chart.yaml` so that it referenced the common chart per file. This can be achieved by running the following command:
```
sed -i 's/repository: https:\/\/bjw-s-labs.github.io\/helm-charts/repository: file:\/\/..\/..\/library\/common\//' helm-charts-common-4.0.1/charts/other/app-template/Chart.yaml
```
So the file `helm-charts-common-4.0.1/charts/other/app-template/Chart.yaml` looked like this:
```
---
apiVersion: v2
description: A common powered chart template. This can be useful for small projects that don't have their own chart.
name: app-template
version: 4.0.1
kubeVersion: ">=1.28.0-0"
maintainers:
  - name: bjw-s
    email: me@bjw-s.dev
dependencies:
  - name: common
    repository: file://../../library/common/
    version: 4.0.1
sources:
  - https://github.com/bjw-s-labs/helm-charts
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: |-
        Upgraded the common library to v4.0.1
      links:
        - name: Upgrade notes
          url: https://bjw-s-labs.github.io/helm-charts/docs/app-template/upgrade-instructions/
        - name: Detailed release notes
          url: https://github.com/bjw-s-labs/helm-charts/releases/tag/common-4.0.1
```
Then I ran the helm command:
```
helm template dummy-release-name ./helm-charts-common-4.0.1/charts/other/app-template/
```
Which returned in the output:
> Error: values don't meet the specifications of the schema(s) in the following chart(s):
> app-template: 
> common:

I tested this without internet connection, so the http GET calls timed out.

**What did you expect to happen:**
I expected the app-template chart to be able to get templated by helm offline.

**Anything else you would like to add:**
In my test environment I will not be able to add https://bjw-s-labs.github.io/helm-charts as helm repository.

**Additional Information:**
