### ISSUE TITLE
Requesting support for volumeDevices

### ISSUE THREAD

**Issue by vishwabmc** [bjw-s-labs/helm-charts#421]
# Details

**Describe the solution you'd like:**
I am looking for a solution like this:

```
persistence:
  test:
    enabled: true
    volumeMode: Block
    type: persistentVolumeClaim
```

As a result of this, I want below to be in effect.

```
volumeDevices:
- name: test
  devicePath: /dev/block-device
```

Also; I am looking for a case where I can directly add this below in the main container. 

```
volumeDevices:
- name: test
  devicePath: /dev/block-device
```

I can add this to 'initContainers`. However, when I add this to main container, I don't see it doing anything.

We are deploying a workload inside Confidential Computing enabled Kata containers, and hence the `volumeMount` does not work since CoCo only works with Block devices.

**Anything else you would like to add:**

**Additional Information:**
