### ISSUE TITLE
Unexpected namespace in ClusterRole/ClusterRoleBinding and missing ServiceAccount when deploying Diun with Helm

### ISSUE THREAD

**Issue by ElGranLoky** [bjw-s-labs/helm-charts#424]
📋 Details

❓ What steps did you take and what happened:
I'm trying to deploy Diun using Helm by creating the necessary RBAC resources as outlined in the [Diun Kubernetes deployment guide](https://crazymax.dev/diun/providers/kubernetes/).

This is the expected configuration:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: diun
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: diun
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: diun
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: diun
subjects:
  - kind: ServiceAccount
    name: diun
    namespace: default
```

I'm using the following Helm values:

```
enforceServiceAccountCreation: false

ServiceAccount:
  create: true
  annotations: {}
  labels: {}
  name: diun
  extraServiceAccounts: {}
```
```
rbac:
  roles:
    role1:
      forceRename: diun
      enabled: true
      type: ClusterRole
      rules:
        - apiGroups: [""]
          resources: ["pods"]
          verbs: ["get", "list", "watch"]
  bindings:
    binding1:
      forceRename: diun
      enabled: true
      type: ClusterRoleBinding
      roleRef:
        name: diun
        kind: ClusterRole
        identifier: rbac.authorization.k8s.io
      subjects:
        - kind: ServiceAccount
          name: diun
          namespace: actualizaciones
```
⚠️ Issues Encountered
When I render the Helm templates, I get the following output:

```
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: diun
    namespace: actualizaciones  # <- This should NOT be present
  ...
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: diun
    namespace: actualizaciones  # <- This should NOT be present
  ...
  subjects:
    - kind: ServiceAccount
      name: diun
      namespace: actualizaciones
```
The namespace field is being added to ClusterRole and ClusterRoleBinding, which should not have a namespace.

The ServiceAccount resource is not being generated at all.

✅ What did you expect to happen:
The resulting YAML should match the format provided in the Diun documentation — with:

A ClusterRole and ClusterRoleBinding without a namespace.

A ServiceAccount properly created as specified in the values.

ℹ️ Additional Information
I'm using the [common Helm library](https://github.com/bjw-s/helm-charts) as a dependency:

```
dependencies:
  - name: common
    version: 3.7.3
    repository: https://bjw-s-labs.github.io/helm-charts/
```
Any guidance on what I might be doing wrong or how to configure this properly would be greatly appreciated. 🙏
